#server:
#  port: 8764
#spring:
#  application:
#    name: eureka-server
#
#sureka:
#  server:
#    waitTimeInMsWhenSyncEmpty: 0
#    enableSelfPreservation: false
#    remoteRegionUrlWithNae:
#      region-west: http://localhost:8761/eureka/
#  client:
#    register-with-eureka: true
#    fetch--registry: true
#    region: region-west
#    service-url:
#      zone3: http://localhost:8763/eureka/
#      zone4: http://localhost:8764/eureka/
#      availability-zones:
#        region-east:zone3,zone4
#  instance:
#    hostname: localhost
#    metadataMap.zone: zone4